[package]
name = "which_option"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.14", features = ["canvas", "tokio"]}
nalgebra = "0.34.1"
statrs = "0.18.0"
plotters="0.3"
plotters-iced2 = "0.14"